version: '3.8'

services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./httpdocs:/var/www/html
      - ./vendor:/var/www/vendor
      - ./.env:/var/www/.env
    container_name: php-docker
